"""
TFS File Parser Module

This module provides functionality to parse a TFS XML file generated by the iFLM software.
It extracts metadata, channel information, and image data in the file.
"""

import logging
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field


logger = logging.getLogger(__name__)


CHANNEL_WAVELENGTH_MAP = {
    "blue": 385,
    "lime": 470,
    "red": 565,
    "magenta": 625,
    "grey": None,        # Reflection channel - wavelength extracted from filename
    "gray": None,        # Reflection channel - wavelength extracted from filename
    "reflection": None,  # Reflection channel (non-iFLM TFS software naming)
}

@dataclass
class ChannelInfo:
    """Data class to store channel information from the TFS file."""

    name: str
    guid: str
    index: int
    color: Tuple[int, int, int, int]    # (A, R, G, B)
    camera_bits: int
    additive: bool
    wavelength: Optional[int] = field(default=None)  # Wavelength in nm (auto-populated)

    def __post_init__(self):
        """Auto-populate wavelength based on channel name."""
        if self.wavelength is None:
            # Look up wavelength from channel name
            name_lower = self.name.lower()
            self.wavelength = CHANNEL_WAVELENGTH_MAP.get(name_lower)
            
            # Log if wavelength was found
            if self.wavelength:
                logger.debug(f"Channel '{self.name}': wavelength={self.wavelength}nm")
            else:
                logger.debug(f"Channel '{self.name}': no wavelength mapping found")

    def __repr__(self) -> str:
        wavelength_str = f"{self.wavelength}nm" if self.wavelength else "None"
        return (
            f"ChannelInfo(name={self.name!r}, index={self.index}, "
            f"wavelength={wavelength_str}, color={self.color})"
        )


@dataclass
class PositionInfo:
    """Data class to store position information from the TFS file.

    R (stage rotation) is optional: some TFS software omits it from
    <sem:Position>, and nothing downstream consumes it.
    """

    x: float
    y: float
    z: float
    at: float
    focus: float
    r: Optional[float] = field(default=None)

    def __repr__(self) -> str:
        return (f"PositionInfo(x={self.x}, y={self.y}, z={self.z}, "
                f"focus={self.focus})")
    

@dataclass
class ImageInfo:
    """Data class to store image metadata from the TFS file."""

    guid: str
    channel_index: int
    plane_index: int
    row: int
    column: int
    time_frame: int
    position: PositionInfo
    relative_path: str
    timestamp: str

    def __repr__(self) -> str:
        return (f"ImageInfo(channel={self.channel_index}, plane={self.plane_index}, "
                f"path='{self.relative_path}')")


class TFSFileParser:
    """Parser for TFS XML files generated by iFLM software."""

    def __init__(self, tfs_file_path: Path):
        """
        Initialize the TFS parser with a file path.
        
        :param tfs_file_path: Path to the TFS XML file
        """
        self.tfs_file_path = Path(tfs_file_path)

        if not self.tfs_file_path.exists():
            raise FileNotFoundError(f"TFS file not found: {self.tfs_file_path}")
        
        # Parse the XML file
        self.tree = ET.parse(self.tfs_file_path)
        self.root = self.tree.getroot()

        # Define namespace mapping for TFS files
        self.namespaces = {
            'maps': 'http://www.thermofisher.com/schemas/maps',
            'sem': 'http://www.thermofisher.com/schemas/sem'
        }

        # Cache parsed data
        self._channels: Optional[List[ChannelInfo]] = None
        self._images: Optional[List[ImageInfo]] = None

        # Reasons for every <Image> entry that had to be dropped during
        # parsing.  A dropped entry silently shifts the z-plane sequence, so
        # callers (upfront validation) check this and refuse to process.
        self.dropped_images: List[str] = []

        logger.info(f"Successfully loaded TFS file: {self.tfs_file_path.name}")

    def get_channels(self) -> List[ChannelInfo]:
        """
        Parse and extract channel information from the TFS file.
        
        :return: List of ChannelInfo objects containing channel metadata
        """
        if self._channels is not None:
            return self._channels
        
        channels = []

        # Find the first ImageMatrix element (not the MIP one)
        image_matrix = self.root.find('.//ImageMatrix')
        
        if image_matrix is None:
            logger.warning("No ImageMatrix element found in TFS file")
            return channels
        
        # Find the Channels section within the first ImageMatrix
        channels_element = image_matrix.find('Channels')

        if channels_element is None:
            logger.warning("No Channels element found in ImageMatrix")
            return channels

        # Parse each Channel
        for channel_elem in channels_element.findall('Channel'):
            try:
                name_elem = channel_elem.find('Name')
                guid_elem = channel_elem.find('Guid')
                index_elem = channel_elem.find('Index')

                if name_elem is None or guid_elem is None or index_elem is None:
                    logger.warning("Channel missing required elements (Name, Guid, Index) - skipping channel")
                    continue

                name = name_elem.text
                guid = guid_elem.text
                index = int(index_elem.text)

                # Color / CameraBits / Additive are carried along but not used by the
                # processing pipeline, so a channel is not dropped when they are absent.
                color = (255, 255, 255, 255)
                color_elem = channel_elem.find('Color')
                if color_elem is not None:
                    a_elem = color_elem.find('A')
                    r_elem = color_elem.find('R')
                    g_elem = color_elem.find('G')
                    b_elem = color_elem.find('B')
                    if all(x is not None for x in [a_elem, r_elem, g_elem, b_elem]):
                        color = (
                            int(a_elem.text),
                            int(r_elem.text),
                            int(g_elem.text),
                            int(b_elem.text)
                        )
                    else:
                        logger.warning(f"Channel '{name}' missing color components - using default color")
                else:
                    logger.warning(f"Channel '{name}' missing Color element - using default color")

                camera_bits_elem = channel_elem.find('CameraBits')
                additive_elem = channel_elem.find('Additive')

                camera_bits = int(camera_bits_elem.text) if camera_bits_elem is not None else 0
                additive = additive_elem.text.lower() == 'true' if additive_elem is not None else False

                # Create ChannelInfo object
                channel_info = ChannelInfo(
                    name=name,
                    guid=guid,
                    index=index,
                    color=color,
                    camera_bits=camera_bits,
                    additive=additive
                )

                channels.append(channel_info)
                logger.debug(f"Parsed channel: {channel_info}")

            except (AttributeError, ValueError) as e:
                logger.error(f"Error parsing channel element: {e}", exc_info=True)
                continue

        self._channels = channels
        logger.info(f"Parsed {len(channels)} channels from TFS file")
        return channels
    
    def get_images(self) -> List[ImageInfo]:
        """
        Parse and extract image metadata from the TFS file.
        
        :return: List of ImageInfo objects containing image metadata
        """
        if self._images is not None:
            return self._images
        
        images = []

        # Find the first ImageMatrix element (not the MIP one)
        image_matrix = self.root.find('.//ImageMatrix')

        if image_matrix is None:
            logger.warning("No ImageMatrix element found in TFS file")
            return images
        
        # Find the Image section
        images_element = image_matrix.find('Images')

        if images_element is None:
            logger.warning("No Images element found in ImageMatrix")
            return images
        
        # Parse each Image
        for image_elem in images_element.findall('Image'):
            try:
                image_info = self._parse_image_element(image_elem)
                if image_info:
                    images.append(image_info)

            except (AttributeError, ValueError) as e:
                logger.error(f"Error parsing image element: {e}", exc_info=True)
                self._drop_image(image_elem, f"parse error: {e}")
                continue
        
        self._images = images
        logger.info(f"Parsed {len(images)} images from TFS file")
        return images
    
    def _drop_image(self, image_elem: ET.Element, reason: str):
        """Record (and log) an <Image> entry that could not be parsed."""
        guid_elem = image_elem.find('Guid')
        guid = guid_elem.text if guid_elem is not None else "<no guid>"
        self.dropped_images.append(f"Image {guid}: {reason}")
        logger.warning(f"Image {guid}: {reason} - entry dropped")

    def _parse_image_element(self, image_elem: ET.Element) -> Optional[ImageInfo]:
        """Parse a single Image element.  Returns None (and records the drop) if invalid."""

        # Get GUID
        guid_elem = image_elem.find('Guid')
        if guid_elem is None:
            self._drop_image(image_elem, "missing Guid")
            return None
        guid = guid_elem.text

        # Parse Index section
        index_elem = image_elem.find('Index')
        if index_elem is None:
            self._drop_image(image_elem, "missing Index element")
            return None

        row_elem = index_elem.find('Row')
        column_elem = index_elem.find('Column')
        channel_elem = index_elem.find('Channel')
        plane_elem = index_elem.find('Plane')
        time_frame_elem = index_elem.find('TimeFrame')

        if any(e is None for e in [row_elem, column_elem, channel_elem, plane_elem, time_frame_elem]):
            self._drop_image(image_elem, "missing Index children (Row/Column/Channel/Plane/TimeFrame)")
            return None

        row = int(row_elem.text)
        column = int(column_elem.text)
        channel_index = int(channel_elem.text)
        plane_index = int(plane_elem.text)
        time_frame = int(time_frame_elem.text)

        # Parse Position section
        position_wrapper = image_elem.find('Position')
        if position_wrapper is None:
            self._drop_image(image_elem, "missing Position wrapper element")
            return None

        # Find the actual sem:Position element
        position_elem = position_wrapper.find('sem:Position', self.namespaces)
        if position_elem is None:
            self._drop_image(image_elem, "missing sem:Position element")
            return None
        
        # The child elements (X, Y, Z, etc.) do not have the sem: prefix
        x_elem = position_elem.find('X')
        y_elem = position_elem.find('Y')
        z_elem = position_elem.find('Z')
        at_elem = position_elem.find('AT')
        focus_elem = position_elem.find('Focus')

        if any(e is None for e in [x_elem, y_elem, z_elem, at_elem, focus_elem]):
            self._drop_image(image_elem, "missing position components (X/Y/Z/AT/Focus)")
            return None

        # R (stage rotation) is optional - some TFS software omits it
        r_elem = position_elem.find('R')

        position = PositionInfo(
            x=float(x_elem.text),
            y=float(y_elem.text),
            z=float(z_elem.text),
            at=float(at_elem.text),
            focus=float(focus_elem.text),
            r=float(r_elem.text) if r_elem is not None else None
        )

        # Get RelativePath
        relative_path_elem = image_elem.find('RelativePath')
        if relative_path_elem is None:
            self._drop_image(image_elem, "missing RelativePath element")
            return None
        relative_path = relative_path_elem.text
        if not relative_path or not relative_path.strip():
            self._drop_image(image_elem, "empty RelativePath")
            return None

        # Get Time
        time_elem = image_elem.find('Time')
        timestamp = time_elem.text if time_elem is not None else ""

        return ImageInfo(
            guid=guid,
            channel_index=channel_index,
            plane_index=plane_index,
            row=row,
            column=column,
            time_frame=time_frame,
            position=position,
            relative_path=relative_path,
            timestamp=timestamp
        )
    
    def get_images_for_channel(self, channel_index: int) -> List[ImageInfo]:
        """
        Get all images for a specific channel, sorted by plane index.
        
        :param channel_index: The channel index (0, 1, 2, etc.)
        :return: List of ImageInfo objects for this channel, sorted by plane
        """
        all_images = self.get_images()
        channel_images = [img for img in all_images if img.channel_index == channel_index]

        # Sort by plane index
        channel_images.sort(key=lambda img: img.plane_index)

        logger.debug(f"Found {len(channel_images)} images for channel {channel_index}")

        return channel_images
    
    def get_focus_values_for_channel(self, channel_index: int) -> List[float]:
        """
        Get focus values for a channel in plane order.
        
        :param channel_index: The channel index
        :return: List of focus values for this channel's images
        """
        images = self.get_images_for_channel(channel_index)
        return [img.position.focus for img in images]
    
    def _extract_wavelength_from_reflection_filename(self, filename: str) -> Optional[int]:
        """
        Extract wavelength from reflection image filename.
        E.g., 'stack_z000_L470_refl.tif' -> 470
        
        :param filename: The image filename
        :return: Wavelength in nm, or None if not found
        """
        # Pattern: L followed by digits, then _refl
        match = re.search(r'L(\d+)_refl', filename)
        if match:
            return int(match.group(1))
        return None
    
    def get_reflection_wavelength(self, channel_index: int) -> Optional[int]:
        """
        Get the wavelength used for reflection channel images.
        Extracts from the first valid reflection image filename.
        
        :param channel_index: The channel index
        :return: Wavelength in nm, or None if not a reflection channel
        """
        images = self.get_images_for_channel(channel_index)
        if not images:
            return None
        
        # Check first image filename for reflection wavelength
        first_image_path = images[0].relative_path
        filename = Path(first_image_path).name
        
        if '_refl' in filename.lower():
            wavelength = self._extract_wavelength_from_reflection_filename(filename)
            if wavelength:
                logger.debug(f"Detected reflection wavelength: {wavelength}nm")
                return wavelength
        
        return None

    def get_image_paths_for_channel(self, channel_index: int) -> List[Path]:
        """
        Get absolute paths to TIFF images for a channel, in plane order.

        Paths are NOT checked for existence here - callers are expected to
        verify existence and fail loudly, so that missing source images can
        never silently desynchronize the pipeline from the XML metadata.

        :param channel_index: The channel index
        :return: List of Path objects for this channel's images
        """
        images = self.get_images_for_channel(channel_index)
        tfs_dir = self.tfs_file_path.parent

        return [tfs_dir / img.relative_path for img in images]

    def get_missing_image_paths_for_channel(self, channel_index: int) -> List[Path]:
        """
        Get the subset of a channel's image paths that do not exist on disk.

        :param channel_index: The channel index
        :return: List of Path objects referenced by the XML but missing from disk
        """
        return [p for p in self.get_image_paths_for_channel(channel_index) if not p.exists()]